// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: activity.sql

package db

import (
	"context"
	"database/sql"
)

const getActivityStats = `-- name: GetActivityStats :one
SELECT
    (SELECT COUNT(*) FROM calls c1 WHERE c1.date_time >= ?1) AS calls_today,
    (SELECT COUNT(*) FROM calls c4 WHERE c4.date_time >= ?2 AND c4.date_time < ?3) AS calls_yesterday,
    (SELECT COUNT(*) FROM calls c2 WHERE c2.date_time >= ?4) AS calls_this_week,
    (SELECT COUNT(*) FROM calls) AS calls_total,
    CAST((SELECT COALESCE(MAX(c3.date_time), 0) FROM calls c3) AS INTEGER) AS last_call_at
`

type GetActivityStatsParams struct {
	TodayStart     int64 `db:"today_start" json:"today_start"`
	YesterdayStart int64 `db:"yesterday_start" json:"yesterday_start"`
	YesterdayUntil int64 `db:"yesterday_until" json:"yesterday_until"`
	WeekStart      int64 `db:"week_start" json:"week_start"`
}

type GetActivityStatsRow struct {
	CallsToday     int64 `db:"calls_today" json:"calls_today"`
	CallsYesterday int64 `db:"calls_yesterday" json:"calls_yesterday"`
	CallsThisWeek  int64 `db:"calls_this_week" json:"calls_this_week"`
	CallsTotal     int64 `db:"calls_total" json:"calls_total"`
	LastCallAt     int64 `db:"last_call_at" json:"last_call_at"`
}

// Returns aggregate stats: today's calls, yesterday's calls up to the same
// time of day (a fair comparison while today is still running), this
// week's calls, total calls and when the newest call was made.
func (q *Queries) GetActivityStats(ctx context.Context, arg GetActivityStatsParams) (GetActivityStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getActivityStats,
		arg.TodayStart,
		arg.YesterdayStart,
		arg.YesterdayUntil,
		arg.WeekStart,
	)
	var i GetActivityStatsRow
	err := row.Scan(
		&i.CallsToday,
		&i.CallsYesterday,
		&i.CallsThisWeek,
		&i.CallsTotal,
		&i.LastCallAt,
	)
	return i, err
}

const getCallsPerHour = `-- name: GetCallsPerHour :many
SELECT
    (date_time / 3600) * 3600 AS hour_bucket,
    COUNT(*) AS call_count
FROM calls
WHERE date_time >= ?
GROUP BY hour_bucket
ORDER BY hour_bucket ASC
`

type GetCallsPerHourRow struct {
	HourBucket int64 `db:"hour_bucket" json:"hour_bucket"`
	CallCount  int64 `db:"call_count" json:"call_count"`
}

// Returns call count per hour for the last 24 hours (24 rows, one per hour bucket).
func (q *Queries) GetCallsPerHour(ctx context.Context, dateTime int64) ([]GetCallsPerHourRow, error) {
	rows, err := q.db.QueryContext(ctx, getCallsPerHour, dateTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCallsPerHourRow{}
	for rows.Next() {
		var i GetCallsPerHourRow
		if err := rows.Scan(&i.HourBucket, &i.CallCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopTalkgroups = `-- name: GetTopTalkgroups :many
SELECT
    c.talkgroup_id,
    c.system_id,
    t.talkgroup_id AS talkgroup_number,
    t.label AS talkgroup_label,
    t.name AS talkgroup_name,
    s.label AS system_label,
    COUNT(*) AS call_count
FROM calls c
LEFT JOIN talkgroups t ON t.id = c.talkgroup_id
LEFT JOIN systems s ON s.id = c.system_id
WHERE c.date_time >= ?
GROUP BY c.talkgroup_id
ORDER BY call_count DESC
LIMIT ?
`

type GetTopTalkgroupsParams struct {
	DateTime int64 `db:"date_time" json:"date_time"`
	Limit    int64 `db:"limit" json:"limit"`
}

type GetTopTalkgroupsRow struct {
	TalkgroupID     sql.NullInt64  `db:"talkgroup_id" json:"talkgroup_id"`
	SystemID        int64          `db:"system_id" json:"system_id"`
	TalkgroupNumber sql.NullInt64  `db:"talkgroup_number" json:"talkgroup_number"`
	TalkgroupLabel  sql.NullString `db:"talkgroup_label" json:"talkgroup_label"`
	TalkgroupName   sql.NullString `db:"talkgroup_name" json:"talkgroup_name"`
	SystemLabel     sql.NullString `db:"system_label" json:"system_label"`
	CallCount       int64          `db:"call_count" json:"call_count"`
}

// Returns top N busiest talkgroups (by call count) in a time range.
func (q *Queries) GetTopTalkgroups(ctx context.Context, arg GetTopTalkgroupsParams) ([]GetTopTalkgroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopTalkgroups, arg.DateTime, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopTalkgroupsRow{}
	for rows.Next() {
		var i GetTopTalkgroupsRow
		if err := rows.Scan(
			&i.TalkgroupID,
			&i.SystemID,
			&i.TalkgroupNumber,
			&i.TalkgroupLabel,
			&i.TalkgroupName,
			&i.SystemLabel,
			&i.CallCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
