// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: bookmarks.sql

package db

import (
	"context"
	"database/sql"
)

const createBookmark = `-- name: CreateBookmark :one
INSERT INTO bookmarks (call_id, user_id, session_id, created_at)
VALUES (?1, ?2, ?3, ?4)
RETURNING id
`

type CreateBookmarkParams struct {
	CallID    int64          `db:"call_id" json:"call_id"`
	UserID    sql.NullInt64  `db:"user_id" json:"user_id"`
	SessionID sql.NullString `db:"session_id" json:"session_id"`
	CreatedAt int64          `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createBookmark,
		arg.CallID,
		arg.UserID,
		arg.SessionID,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteBookmarkByCallAndUser = `-- name: DeleteBookmarkByCallAndUser :exec
DELETE FROM bookmarks WHERE call_id = ? AND user_id = ?
`

type DeleteBookmarkByCallAndUserParams struct {
	CallID int64         `db:"call_id" json:"call_id"`
	UserID sql.NullInt64 `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteBookmarkByCallAndUser(ctx context.Context, arg DeleteBookmarkByCallAndUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteBookmarkByCallAndUser, arg.CallID, arg.UserID)
	return err
}

const getBookmarkByCallAndUser = `-- name: GetBookmarkByCallAndUser :one
SELECT id, call_id, user_id, session_id, created_at FROM bookmarks WHERE call_id = ? AND user_id = ? LIMIT 1
`

type GetBookmarkByCallAndUserParams struct {
	CallID int64         `db:"call_id" json:"call_id"`
	UserID sql.NullInt64 `db:"user_id" json:"user_id"`
}

func (q *Queries) GetBookmarkByCallAndUser(ctx context.Context, arg GetBookmarkByCallAndUserParams) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, getBookmarkByCallAndUser, arg.CallID, arg.UserID)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.UserID,
		&i.SessionID,
		&i.CreatedAt,
	)
	return i, err
}

const listBookmarkCallIDsByUser = `-- name: ListBookmarkCallIDsByUser :many
SELECT call_id FROM bookmarks WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListBookmarkCallIDsByUser(ctx context.Context, userID sql.NullInt64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listBookmarkCallIDsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var call_id int64
		if err := rows.Scan(&call_id); err != nil {
			return nil, err
		}
		items = append(items, call_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookmarkCallsByUser = `-- name: ListBookmarkCallsByUser :many
SELECT
    c.id, c.audio_path, c.audio_name, c.audio_type, c.date_time, c.frequency, c.duration, c.source, c.sources_json, c.frequencies_json, c.patches_json, c.system_id, c.talkgroup_id, c.site, c.channel, c.decoder, c.error_count, c.spike_count, c.talker_alias, c.api_key_id,
    s.label AS system_label,
    s.system_id AS system_radio_id,
    t.label AS talkgroup_label,
    t.name  AS talkgroup_name,
    t.led   AS talkgroup_led,
    t.talkgroup_id AS talkgroup_radio_id,
    tr.text AS transcript_text
FROM bookmarks b
JOIN calls c ON c.id = b.call_id
LEFT JOIN systems s ON s.id = c.system_id
LEFT JOIN talkgroups t ON t.id = c.talkgroup_id
LEFT JOIN transcriptions tr ON tr.call_id = c.id
WHERE b.user_id = ?
ORDER BY b.created_at DESC
LIMIT 100
`

type ListBookmarkCallsByUserRow struct {
	ID               int64          `db:"id" json:"id"`
	AudioPath        string         `db:"audio_path" json:"audio_path"`
	AudioName        string         `db:"audio_name" json:"audio_name"`
	AudioType        string         `db:"audio_type" json:"audio_type"`
	DateTime         int64          `db:"date_time" json:"date_time"`
	Frequency        sql.NullInt64  `db:"frequency" json:"frequency"`
	Duration         sql.NullInt64  `db:"duration" json:"duration"`
	Source           sql.NullInt64  `db:"source" json:"source"`
	SourcesJson      sql.NullString `db:"sources_json" json:"sources_json"`
	FrequenciesJson  sql.NullString `db:"frequencies_json" json:"frequencies_json"`
	PatchesJson      sql.NullString `db:"patches_json" json:"patches_json"`
	SystemID         int64          `db:"system_id" json:"system_id"`
	TalkgroupID      sql.NullInt64  `db:"talkgroup_id" json:"talkgroup_id"`
	Site             sql.NullString `db:"site" json:"site"`
	Channel          sql.NullString `db:"channel" json:"channel"`
	Decoder          sql.NullString `db:"decoder" json:"decoder"`
	ErrorCount       sql.NullInt64  `db:"error_count" json:"error_count"`
	SpikeCount       sql.NullInt64  `db:"spike_count" json:"spike_count"`
	TalkerAlias      sql.NullString `db:"talker_alias" json:"talker_alias"`
	ApiKeyID         sql.NullInt64  `db:"api_key_id" json:"api_key_id"`
	SystemLabel      sql.NullString `db:"system_label" json:"system_label"`
	SystemRadioID    sql.NullInt64  `db:"system_radio_id" json:"system_radio_id"`
	TalkgroupLabel   sql.NullString `db:"talkgroup_label" json:"talkgroup_label"`
	TalkgroupName    sql.NullString `db:"talkgroup_name" json:"talkgroup_name"`
	TalkgroupLed     sql.NullString `db:"talkgroup_led" json:"talkgroup_led"`
	TalkgroupRadioID sql.NullInt64  `db:"talkgroup_radio_id" json:"talkgroup_radio_id"`
	TranscriptText   sql.NullString `db:"transcript_text" json:"transcript_text"`
}

func (q *Queries) ListBookmarkCallsByUser(ctx context.Context, userID sql.NullInt64) ([]ListBookmarkCallsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listBookmarkCallsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookmarkCallsByUserRow{}
	for rows.Next() {
		var i ListBookmarkCallsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.AudioPath,
			&i.AudioName,
			&i.AudioType,
			&i.DateTime,
			&i.Frequency,
			&i.Duration,
			&i.Source,
			&i.SourcesJson,
			&i.FrequenciesJson,
			&i.PatchesJson,
			&i.SystemID,
			&i.TalkgroupID,
			&i.Site,
			&i.Channel,
			&i.Decoder,
			&i.ErrorCount,
			&i.SpikeCount,
			&i.TalkerAlias,
			&i.ApiKeyID,
			&i.SystemLabel,
			&i.SystemRadioID,
			&i.TalkgroupLabel,
			&i.TalkgroupName,
			&i.TalkgroupLed,
			&i.TalkgroupRadioID,
			&i.TranscriptText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookmarksByUser = `-- name: ListBookmarksByUser :many
SELECT id, call_id, user_id, session_id, created_at FROM bookmarks WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListBookmarksByUser(ctx context.Context, userID sql.NullInt64) ([]Bookmark, error) {
	rows, err := q.db.QueryContext(ctx, listBookmarksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bookmark{}
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.UserID,
			&i.SessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
