// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: calls.sql

package db

import (
	"context"
	"database/sql"
)

const countCalls = `-- name: CountCalls :one
SELECT COUNT(*) FROM calls
`

func (q *Queries) CountCalls(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCalls)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCallsFiltered = `-- name: CountCallsFiltered :one
SELECT COUNT(*)
FROM calls c
LEFT JOIN talkgroups tg ON tg.id = c.talkgroup_id
LEFT JOIN transcriptions tr ON tr.call_id = c.id
WHERE
    (?1 IS NULL OR instr(',' || ?1 || ',', ',' || c.system_id || ',') > 0)
    AND (?2 IS NULL OR instr(',' || ?2 || ',', ',' || c.talkgroup_id || ',') > 0)
    AND (?3 IS NULL OR instr(',' || ?3 || ',', ',' || tg.group_id || ',') > 0)
    AND (?4 IS NULL OR instr(',' || ?4 || ',', ',' || tg.tag_id || ',') > 0)
    AND (?5    IS NULL OR c.date_time    >= ?5)
    AND (?6      IS NULL OR c.date_time    <= ?6)
    AND (?7 IS NULL OR EXISTS (
        SELECT 1 FROM bookmarks b WHERE b.call_id = c.id AND b.user_id = ?7
    ))
    AND (?8   IS NULL OR tr.text LIKE '%' || ?8 || '%')
`

type CountCallsFilteredParams struct {
	SystemIdsCsv    interface{} `db:"system_ids_csv" json:"system_ids_csv"`
	TalkgroupIdsCsv interface{} `db:"talkgroup_ids_csv" json:"talkgroup_ids_csv"`
	GroupIdsCsv     interface{} `db:"group_ids_csv" json:"group_ids_csv"`
	TagIdsCsv       interface{} `db:"tag_ids_csv" json:"tag_ids_csv"`
	DateFrom        interface{} `db:"date_from" json:"date_from"`
	DateTo          interface{} `db:"date_to" json:"date_to"`
	BookmarkUserID  interface{} `db:"bookmark_user_id" json:"bookmark_user_id"`
	Transcript      interface{} `db:"transcript" json:"transcript"`
}

func (q *Queries) CountCallsFiltered(ctx context.Context, arg CountCallsFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCallsFiltered,
		arg.SystemIdsCsv,
		arg.TalkgroupIdsCsv,
		arg.GroupIdsCsv,
		arg.TagIdsCsv,
		arg.DateFrom,
		arg.DateTo,
		arg.BookmarkUserID,
		arg.Transcript,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCallsPerAPIKeySince = `-- name: CountCallsPerAPIKeySince :many
SELECT api_key_id, COUNT(*) AS calls
FROM calls
WHERE api_key_id IS NOT NULL AND date_time >= ?
GROUP BY api_key_id
`

type CountCallsPerAPIKeySinceRow struct {
	ApiKeyID sql.NullInt64 `db:"api_key_id" json:"api_key_id"`
	Calls    int64         `db:"calls" json:"calls"`
}

func (q *Queries) CountCallsPerAPIKeySince(ctx context.Context, dateTime int64) ([]CountCallsPerAPIKeySinceRow, error) {
	rows, err := q.db.QueryContext(ctx, countCallsPerAPIKeySince, dateTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountCallsPerAPIKeySinceRow{}
	for rows.Next() {
		var i CountCallsPerAPIKeySinceRow
		if err := rows.Scan(&i.ApiKeyID, &i.Calls); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCall = `-- name: CreateCall :one
INSERT INTO calls (
    audio_path,
    audio_name,
    audio_type,
    date_time,
    frequency,
    duration,
    source,
    sources_json,
    frequencies_json,
    patches_json,
    system_id,
    talkgroup_id,
    site,
    channel,
    decoder,
    error_count,
    spike_count,
    talker_alias,
    api_key_id
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13,
    ?14,
    ?15,
    ?16,
    ?17,
    ?18,
    ?19
) RETURNING id
`

type CreateCallParams struct {
	AudioPath       string         `db:"audio_path" json:"audio_path"`
	AudioName       string         `db:"audio_name" json:"audio_name"`
	AudioType       string         `db:"audio_type" json:"audio_type"`
	DateTime        int64          `db:"date_time" json:"date_time"`
	Frequency       sql.NullInt64  `db:"frequency" json:"frequency"`
	Duration        sql.NullInt64  `db:"duration" json:"duration"`
	Source          sql.NullInt64  `db:"source" json:"source"`
	SourcesJson     sql.NullString `db:"sources_json" json:"sources_json"`
	FrequenciesJson sql.NullString `db:"frequencies_json" json:"frequencies_json"`
	PatchesJson     sql.NullString `db:"patches_json" json:"patches_json"`
	SystemID        int64          `db:"system_id" json:"system_id"`
	TalkgroupID     sql.NullInt64  `db:"talkgroup_id" json:"talkgroup_id"`
	Site            sql.NullString `db:"site" json:"site"`
	Channel         sql.NullString `db:"channel" json:"channel"`
	Decoder         sql.NullString `db:"decoder" json:"decoder"`
	ErrorCount      sql.NullInt64  `db:"error_count" json:"error_count"`
	SpikeCount      sql.NullInt64  `db:"spike_count" json:"spike_count"`
	TalkerAlias     sql.NullString `db:"talker_alias" json:"talker_alias"`
	ApiKeyID        sql.NullInt64  `db:"api_key_id" json:"api_key_id"`
}

func (q *Queries) CreateCall(ctx context.Context, arg CreateCallParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createCall,
		arg.AudioPath,
		arg.AudioName,
		arg.AudioType,
		arg.DateTime,
		arg.Frequency,
		arg.Duration,
		arg.Source,
		arg.SourcesJson,
		arg.FrequenciesJson,
		arg.PatchesJson,
		arg.SystemID,
		arg.TalkgroupID,
		arg.Site,
		arg.Channel,
		arg.Decoder,
		arg.ErrorCount,
		arg.SpikeCount,
		arg.TalkerAlias,
		arg.ApiKeyID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteCallBatch = `-- name: DeleteCallBatch :exec
DELETE FROM calls WHERE id = ?
`

func (q *Queries) DeleteCallBatch(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCallBatch, id)
	return err
}

const getCall = `-- name: GetCall :one
SELECT
    c.id, c.audio_path, c.audio_name, c.audio_type, c.date_time, c.frequency, c.duration, c.source, c.sources_json, c.frequencies_json, c.patches_json, c.system_id, c.talkgroup_id, c.site, c.channel, c.decoder, c.error_count, c.spike_count, c.talker_alias, c.api_key_id,
    s.label  AS system_label,
    t.label  AS talkgroup_label,
    t.name   AS talkgroup_name
FROM calls c
LEFT JOIN systems    s ON s.id = c.system_id
LEFT JOIN talkgroups t ON t.id = c.talkgroup_id
WHERE c.id = ?
LIMIT 1
`

type GetCallRow struct {
	ID              int64          `db:"id" json:"id"`
	AudioPath       string         `db:"audio_path" json:"audio_path"`
	AudioName       string         `db:"audio_name" json:"audio_name"`
	AudioType       string         `db:"audio_type" json:"audio_type"`
	DateTime        int64          `db:"date_time" json:"date_time"`
	Frequency       sql.NullInt64  `db:"frequency" json:"frequency"`
	Duration        sql.NullInt64  `db:"duration" json:"duration"`
	Source          sql.NullInt64  `db:"source" json:"source"`
	SourcesJson     sql.NullString `db:"sources_json" json:"sources_json"`
	FrequenciesJson sql.NullString `db:"frequencies_json" json:"frequencies_json"`
	PatchesJson     sql.NullString `db:"patches_json" json:"patches_json"`
	SystemID        int64          `db:"system_id" json:"system_id"`
	TalkgroupID     sql.NullInt64  `db:"talkgroup_id" json:"talkgroup_id"`
	Site            sql.NullString `db:"site" json:"site"`
	Channel         sql.NullString `db:"channel" json:"channel"`
	Decoder         sql.NullString `db:"decoder" json:"decoder"`
	ErrorCount      sql.NullInt64  `db:"error_count" json:"error_count"`
	SpikeCount      sql.NullInt64  `db:"spike_count" json:"spike_count"`
	TalkerAlias     sql.NullString `db:"talker_alias" json:"talker_alias"`
	ApiKeyID        sql.NullInt64  `db:"api_key_id" json:"api_key_id"`
	SystemLabel     sql.NullString `db:"system_label" json:"system_label"`
	TalkgroupLabel  sql.NullString `db:"talkgroup_label" json:"talkgroup_label"`
	TalkgroupName   sql.NullString `db:"talkgroup_name" json:"talkgroup_name"`
}

func (q *Queries) GetCall(ctx context.Context, id int64) (GetCallRow, error) {
	row := q.db.QueryRowContext(ctx, getCall, id)
	var i GetCallRow
	err := row.Scan(
		&i.ID,
		&i.AudioPath,
		&i.AudioName,
		&i.AudioType,
		&i.DateTime,
		&i.Frequency,
		&i.Duration,
		&i.Source,
		&i.SourcesJson,
		&i.FrequenciesJson,
		&i.PatchesJson,
		&i.SystemID,
		&i.TalkgroupID,
		&i.Site,
		&i.Channel,
		&i.Decoder,
		&i.ErrorCount,
		&i.SpikeCount,
		&i.TalkerAlias,
		&i.ApiKeyID,
		&i.SystemLabel,
		&i.TalkgroupLabel,
		&i.TalkgroupName,
	)
	return i, err
}

const getCallIDsOlderThan = `-- name: GetCallIDsOlderThan :many
SELECT c.id, c.audio_path
FROM calls c
LEFT JOIN bookmarks b ON b.call_id = c.id
LEFT JOIN shared_links sl ON sl.call_id = c.id
WHERE c.date_time < ? AND b.id IS NULL AND sl.id IS NULL
ORDER BY c.date_time ASC
LIMIT 500
`

type GetCallIDsOlderThanRow struct {
	ID        int64  `db:"id" json:"id"`
	AudioPath string `db:"audio_path" json:"audio_path"`
}

func (q *Queries) GetCallIDsOlderThan(ctx context.Context, dateTime int64) ([]GetCallIDsOlderThanRow, error) {
	rows, err := q.db.QueryContext(ctx, getCallIDsOlderThan, dateTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCallIDsOlderThanRow{}
	for rows.Next() {
		var i GetCallIDsOlderThanRow
		if err := rows.Scan(&i.ID, &i.AudioPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasCallAtTimestamp = `-- name: HasCallAtTimestamp :one
SELECT EXISTS(
    SELECT 1
    FROM calls c
    WHERE c.system_id = ? AND c.talkgroup_id = ? AND c.date_time = ?
)
`

type HasCallAtTimestampParams struct {
	SystemID    int64         `db:"system_id" json:"system_id"`
	TalkgroupID sql.NullInt64 `db:"talkgroup_id" json:"talkgroup_id"`
	DateTime    int64         `db:"date_time" json:"date_time"`
}

func (q *Queries) HasCallAtTimestamp(ctx context.Context, arg HasCallAtTimestampParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasCallAtTimestamp, arg.SystemID, arg.TalkgroupID, arg.DateTime)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const hasCallInTimeRange = `-- name: HasCallInTimeRange :one
SELECT EXISTS(
    SELECT 1
    FROM calls c
    WHERE c.system_id = ? AND c.talkgroup_id = ?
      AND c.date_time >= ? AND c.date_time <= ?
)
`

type HasCallInTimeRangeParams struct {
	SystemID    int64         `db:"system_id" json:"system_id"`
	TalkgroupID sql.NullInt64 `db:"talkgroup_id" json:"talkgroup_id"`
	DateTime    int64         `db:"date_time" json:"date_time"`
	DateTime_2  int64         `db:"date_time_2" json:"date_time_2"`
}

func (q *Queries) HasCallInTimeRange(ctx context.Context, arg HasCallInTimeRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasCallInTimeRange,
		arg.SystemID,
		arg.TalkgroupID,
		arg.DateTime,
		arg.DateTime_2,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listCalls = `-- name: ListCalls :many
SELECT c.id, c.audio_path, c.audio_name, c.audio_type, c.date_time, c.frequency, c.duration, c.source, c.sources_json, c.frequencies_json, c.patches_json, c.system_id, c.talkgroup_id, c.site, c.channel, c.decoder, c.error_count, c.spike_count, c.talker_alias, c.api_key_id
FROM calls c
LEFT JOIN talkgroups tg ON tg.id = c.talkgroup_id
LEFT JOIN transcriptions tr ON tr.call_id = c.id
WHERE
    (?1 IS NULL OR instr(',' || ?1 || ',', ',' || c.system_id || ',') > 0)
    AND (?2 IS NULL OR instr(',' || ?2 || ',', ',' || c.talkgroup_id || ',') > 0)
    AND (?3 IS NULL OR instr(',' || ?3 || ',', ',' || tg.group_id || ',') > 0)
    AND (?4 IS NULL OR instr(',' || ?4 || ',', ',' || tg.tag_id || ',') > 0)
    AND (?5    IS NULL OR c.date_time    >= ?5)
    AND (?6      IS NULL OR c.date_time    <= ?6)
    AND (?7 IS NULL OR EXISTS (
        SELECT 1 FROM bookmarks b WHERE b.call_id = c.id AND b.user_id = ?7
    ))
    AND (?8   IS NULL OR tr.text LIKE '%' || ?8 || '%')
ORDER BY c.date_time DESC
LIMIT  ?10
OFFSET ?9
`

type ListCallsParams struct {
	SystemIdsCsv    interface{}   `db:"system_ids_csv" json:"system_ids_csv"`
	TalkgroupIdsCsv interface{}   `db:"talkgroup_ids_csv" json:"talkgroup_ids_csv"`
	GroupIdsCsv     interface{}   `db:"group_ids_csv" json:"group_ids_csv"`
	TagIdsCsv       interface{}   `db:"tag_ids_csv" json:"tag_ids_csv"`
	DateFrom        interface{}   `db:"date_from" json:"date_from"`
	DateTo          interface{}   `db:"date_to" json:"date_to"`
	BookmarkUserID  interface{}   `db:"bookmark_user_id" json:"bookmark_user_id"`
	Transcript      interface{}   `db:"transcript" json:"transcript"`
	PageOffset      sql.NullInt64 `db:"page_offset" json:"page_offset"`
	PageSize        sql.NullInt64 `db:"page_size" json:"page_size"`
}

func (q *Queries) ListCalls(ctx context.Context, arg ListCallsParams) ([]Call, error) {
	rows, err := q.db.QueryContext(ctx, listCalls,
		arg.SystemIdsCsv,
		arg.TalkgroupIdsCsv,
		arg.GroupIdsCsv,
		arg.TagIdsCsv,
		arg.DateFrom,
		arg.DateTo,
		arg.BookmarkUserID,
		arg.Transcript,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Call{}
	for rows.Next() {
		var i Call
		if err := rows.Scan(
			&i.ID,
			&i.AudioPath,
			&i.AudioName,
			&i.AudioType,
			&i.DateTime,
			&i.Frequency,
			&i.Duration,
			&i.Source,
			&i.SourcesJson,
			&i.FrequenciesJson,
			&i.PatchesJson,
			&i.SystemID,
			&i.TalkgroupID,
			&i.Site,
			&i.Channel,
			&i.Decoder,
			&i.ErrorCount,
			&i.SpikeCount,
			&i.TalkerAlias,
			&i.ApiKeyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCallsAsc = `-- name: ListCallsAsc :many
SELECT c.id, c.audio_path, c.audio_name, c.audio_type, c.date_time, c.frequency, c.duration, c.source, c.sources_json, c.frequencies_json, c.patches_json, c.system_id, c.talkgroup_id, c.site, c.channel, c.decoder, c.error_count, c.spike_count, c.talker_alias, c.api_key_id
FROM calls c
LEFT JOIN talkgroups tg ON tg.id = c.talkgroup_id
LEFT JOIN transcriptions tr ON tr.call_id = c.id
WHERE
    (?1 IS NULL OR instr(',' || ?1 || ',', ',' || c.system_id || ',') > 0)
    AND (?2 IS NULL OR instr(',' || ?2 || ',', ',' || c.talkgroup_id || ',') > 0)
    AND (?3 IS NULL OR instr(',' || ?3 || ',', ',' || tg.group_id || ',') > 0)
    AND (?4 IS NULL OR instr(',' || ?4 || ',', ',' || tg.tag_id || ',') > 0)
    AND (?5    IS NULL OR c.date_time    >= ?5)
    AND (?6      IS NULL OR c.date_time    <= ?6)
    AND (?7 IS NULL OR EXISTS (
        SELECT 1 FROM bookmarks b WHERE b.call_id = c.id AND b.user_id = ?7
    ))
    AND (?8   IS NULL OR tr.text LIKE '%' || ?8 || '%')
ORDER BY c.date_time ASC
LIMIT  ?10
OFFSET ?9
`

type ListCallsAscParams struct {
	SystemIdsCsv    interface{}   `db:"system_ids_csv" json:"system_ids_csv"`
	TalkgroupIdsCsv interface{}   `db:"talkgroup_ids_csv" json:"talkgroup_ids_csv"`
	GroupIdsCsv     interface{}   `db:"group_ids_csv" json:"group_ids_csv"`
	TagIdsCsv       interface{}   `db:"tag_ids_csv" json:"tag_ids_csv"`
	DateFrom        interface{}   `db:"date_from" json:"date_from"`
	DateTo          interface{}   `db:"date_to" json:"date_to"`
	BookmarkUserID  interface{}   `db:"bookmark_user_id" json:"bookmark_user_id"`
	Transcript      interface{}   `db:"transcript" json:"transcript"`
	PageOffset      sql.NullInt64 `db:"page_offset" json:"page_offset"`
	PageSize        sql.NullInt64 `db:"page_size" json:"page_size"`
}

func (q *Queries) ListCallsAsc(ctx context.Context, arg ListCallsAscParams) ([]Call, error) {
	rows, err := q.db.QueryContext(ctx, listCallsAsc,
		arg.SystemIdsCsv,
		arg.TalkgroupIdsCsv,
		arg.GroupIdsCsv,
		arg.TagIdsCsv,
		arg.DateFrom,
		arg.DateTo,
		arg.BookmarkUserID,
		arg.Transcript,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Call{}
	for rows.Next() {
		var i Call
		if err := rows.Scan(
			&i.ID,
			&i.AudioPath,
			&i.AudioName,
			&i.AudioType,
			&i.DateTime,
			&i.Frequency,
			&i.Duration,
			&i.Source,
			&i.SourcesJson,
			&i.FrequenciesJson,
			&i.PatchesJson,
			&i.SystemID,
			&i.TalkgroupID,
			&i.Site,
			&i.Channel,
			&i.Decoder,
			&i.ErrorCount,
			&i.SpikeCount,
			&i.TalkerAlias,
			&i.ApiKeyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
