// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: connection_log.sql

package db

import (
	"context"
	"database/sql"
)

const closeConnectionLog = `-- name: CloseConnectionLog :exec
UPDATE connection_log SET disconnected_at = ?, disconnect_reason = ? WHERE id = ?
`

type CloseConnectionLogParams struct {
	DisconnectedAt   sql.NullInt64  `db:"disconnected_at" json:"disconnected_at"`
	DisconnectReason sql.NullString `db:"disconnect_reason" json:"disconnect_reason"`
	ID               int64          `db:"id" json:"id"`
}

func (q *Queries) CloseConnectionLog(ctx context.Context, arg CloseConnectionLogParams) error {
	_, err := q.db.ExecContext(ctx, closeConnectionLog, arg.DisconnectedAt, arg.DisconnectReason, arg.ID)
	return err
}

const closeOpenConnectionLogs = `-- name: CloseOpenConnectionLogs :exec
UPDATE connection_log SET disconnected_at = ?, disconnect_reason = ? WHERE disconnected_at IS NULL
`

type CloseOpenConnectionLogsParams struct {
	DisconnectedAt   sql.NullInt64  `db:"disconnected_at" json:"disconnected_at"`
	DisconnectReason sql.NullString `db:"disconnect_reason" json:"disconnect_reason"`
}

// At startup: rows still open were left by a process that did not shut
// down cleanly. Their real end time is unknown.
func (q *Queries) CloseOpenConnectionLogs(ctx context.Context, arg CloseOpenConnectionLogsParams) error {
	_, err := q.db.ExecContext(ctx, closeOpenConnectionLogs, arg.DisconnectedAt, arg.DisconnectReason)
	return err
}

const countConnectionLog = `-- name: CountConnectionLog :one
SELECT COUNT(*) FROM connection_log
WHERE (?1 IS NULL OR ip = ?1)
  AND (?2 IS NULL OR user_id = ?2)
  AND (?3 IS NULL OR kind = ?3)
  AND (?4 IS NULL OR connected_at >= ?4)
  AND (?5 IS NULL OR connected_at < ?5)
`

type CountConnectionLogParams struct {
	Ip     interface{} `db:"ip" json:"ip"`
	UserID interface{} `db:"user_id" json:"user_id"`
	Kind   interface{} `db:"kind" json:"kind"`
	Since  interface{} `db:"since" json:"since"`
	Until  interface{} `db:"until" json:"until"`
}

func (q *Queries) CountConnectionLog(ctx context.Context, arg CountConnectionLogParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConnectionLog,
		arg.Ip,
		arg.UserID,
		arg.Kind,
		arg.Since,
		arg.Until,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteConnectionLogBefore = `-- name: DeleteConnectionLogBefore :exec
DELETE FROM connection_log WHERE connected_at < ?
`

func (q *Queries) DeleteConnectionLogBefore(ctx context.Context, connectedAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteConnectionLogBefore, connectedAt)
	return err
}

const insertConnectionLog = `-- name: InsertConnectionLog :one
INSERT INTO connection_log (kind, user_id, username, ip, country_code, user_agent, native, family_id, connected_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertConnectionLogParams struct {
	Kind        string         `db:"kind" json:"kind"`
	UserID      sql.NullInt64  `db:"user_id" json:"user_id"`
	Username    sql.NullString `db:"username" json:"username"`
	Ip          string         `db:"ip" json:"ip"`
	CountryCode sql.NullString `db:"country_code" json:"country_code"`
	UserAgent   sql.NullString `db:"user_agent" json:"user_agent"`
	Native      int64          `db:"native" json:"native"`
	FamilyID    sql.NullString `db:"family_id" json:"family_id"`
	ConnectedAt int64          `db:"connected_at" json:"connected_at"`
}

func (q *Queries) InsertConnectionLog(ctx context.Context, arg InsertConnectionLogParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertConnectionLog,
		arg.Kind,
		arg.UserID,
		arg.Username,
		arg.Ip,
		arg.CountryCode,
		arg.UserAgent,
		arg.Native,
		arg.FamilyID,
		arg.ConnectedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listConnectionLog = `-- name: ListConnectionLog :many
SELECT id, kind, user_id, username, ip, country_code, user_agent, native, family_id, connected_at, disconnected_at, disconnect_reason FROM connection_log
WHERE (?1 IS NULL OR ip = ?1)
  AND (?2 IS NULL OR user_id = ?2)
  AND (?3 IS NULL OR kind = ?3)
  AND (?4 IS NULL OR connected_at >= ?4)
  AND (?5 IS NULL OR connected_at < ?5)
ORDER BY connected_at DESC, id DESC
LIMIT ?7 OFFSET ?6
`

type ListConnectionLogParams struct {
	Ip     interface{} `db:"ip" json:"ip"`
	UserID interface{} `db:"user_id" json:"user_id"`
	Kind   interface{} `db:"kind" json:"kind"`
	Since  interface{} `db:"since" json:"since"`
	Until  interface{} `db:"until" json:"until"`
	Offset int64       `db:"offset" json:"offset"`
	Limit  int64       `db:"limit" json:"limit"`
}

func (q *Queries) ListConnectionLog(ctx context.Context, arg ListConnectionLogParams) ([]ConnectionLog, error) {
	rows, err := q.db.QueryContext(ctx, listConnectionLog,
		arg.Ip,
		arg.UserID,
		arg.Kind,
		arg.Since,
		arg.Until,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectionLog{}
	for rows.Next() {
		var i ConnectionLog
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.UserID,
			&i.Username,
			&i.Ip,
			&i.CountryCode,
			&i.UserAgent,
			&i.Native,
			&i.FamilyID,
			&i.ConnectedAt,
			&i.DisconnectedAt,
			&i.DisconnectReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
