// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: downstreams.sql

package db

import (
	"context"
	"database/sql"
)

const createDownstream = `-- name: CreateDownstream :one
INSERT INTO downstreams (
    url,
    api_key,
    systems_json,
    disabled,
    "order",
    label
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
) RETURNING id
`

type CreateDownstreamParams struct {
	Url         string         `db:"url" json:"url"`
	ApiKey      string         `db:"api_key" json:"api_key"`
	SystemsJson sql.NullString `db:"systems_json" json:"systems_json"`
	Disabled    int64          `db:"disabled" json:"disabled"`
	Order       int64          `db:"order" json:"order"`
	Label       string         `db:"label" json:"label"`
}

func (q *Queries) CreateDownstream(ctx context.Context, arg CreateDownstreamParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createDownstream,
		arg.Url,
		arg.ApiKey,
		arg.SystemsJson,
		arg.Disabled,
		arg.Order,
		arg.Label,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteDownstream = `-- name: DeleteDownstream :exec
DELETE FROM downstreams WHERE id = ?
`

func (q *Queries) DeleteDownstream(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDownstream, id)
	return err
}

const getDownstream = `-- name: GetDownstream :one
SELECT id, url, api_key, systems_json, disabled, "order", label, last_at, last_ok, last_status, last_error, last_ok_at FROM downstreams WHERE id = ? LIMIT 1
`

func (q *Queries) GetDownstream(ctx context.Context, id int64) (Downstream, error) {
	row := q.db.QueryRowContext(ctx, getDownstream, id)
	var i Downstream
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.ApiKey,
		&i.SystemsJson,
		&i.Disabled,
		&i.Order,
		&i.Label,
		&i.LastAt,
		&i.LastOk,
		&i.LastStatus,
		&i.LastError,
		&i.LastOkAt,
	)
	return i, err
}

const listActiveDownstreams = `-- name: ListActiveDownstreams :many
SELECT id, url, api_key, systems_json, disabled, "order", label, last_at, last_ok, last_status, last_error, last_ok_at FROM downstreams WHERE disabled = 0 ORDER BY "order" ASC, id ASC
`

func (q *Queries) ListActiveDownstreams(ctx context.Context) ([]Downstream, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDownstreams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Downstream{}
	for rows.Next() {
		var i Downstream
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.ApiKey,
			&i.SystemsJson,
			&i.Disabled,
			&i.Order,
			&i.Label,
			&i.LastAt,
			&i.LastOk,
			&i.LastStatus,
			&i.LastError,
			&i.LastOkAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownstreams = `-- name: ListDownstreams :many
SELECT id, url, api_key, systems_json, disabled, "order", label, last_at, last_ok, last_status, last_error, last_ok_at FROM downstreams ORDER BY "order" ASC, id ASC
`

func (q *Queries) ListDownstreams(ctx context.Context) ([]Downstream, error) {
	rows, err := q.db.QueryContext(ctx, listDownstreams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Downstream{}
	for rows.Next() {
		var i Downstream
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.ApiKey,
			&i.SystemsJson,
			&i.Disabled,
			&i.Order,
			&i.Label,
			&i.LastAt,
			&i.LastOk,
			&i.LastStatus,
			&i.LastError,
			&i.LastOkAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDownstreamDelivery = `-- name: RecordDownstreamDelivery :exec
UPDATE downstreams SET
    last_at     = ?1,
    last_ok     = ?2,
    last_status = ?3,
    last_error  = ?4,
    last_ok_at  = CASE WHEN ?2 = 1 THEN ?1 ELSE last_ok_at END
WHERE id = ?5
`

type RecordDownstreamDeliveryParams struct {
	At     sql.NullInt64 `db:"at" json:"at"`
	Ok     int64         `db:"ok" json:"ok"`
	Status int64         `db:"status" json:"status"`
	Error  string        `db:"error" json:"error"`
	ID     int64         `db:"id" json:"id"`
}

func (q *Queries) RecordDownstreamDelivery(ctx context.Context, arg RecordDownstreamDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, recordDownstreamDelivery,
		arg.At,
		arg.Ok,
		arg.Status,
		arg.Error,
		arg.ID,
	)
	return err
}

const updateDownstream = `-- name: UpdateDownstream :exec
UPDATE downstreams SET
    url          = ?1,
    api_key      = ?2,
    systems_json = ?3,
    disabled     = ?4,
    "order"      = ?5,
    label        = ?6
WHERE id = ?7
`

type UpdateDownstreamParams struct {
	Url         string         `db:"url" json:"url"`
	ApiKey      string         `db:"api_key" json:"api_key"`
	SystemsJson sql.NullString `db:"systems_json" json:"systems_json"`
	Disabled    int64          `db:"disabled" json:"disabled"`
	Order       int64          `db:"order" json:"order"`
	Label       string         `db:"label" json:"label"`
	ID          int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateDownstream(ctx context.Context, arg UpdateDownstreamParams) error {
	_, err := q.db.ExecContext(ctx, updateDownstream,
		arg.Url,
		arg.ApiKey,
		arg.SystemsJson,
		arg.Disabled,
		arg.Order,
		arg.Label,
		arg.ID,
	)
	return err
}
