// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ip_blocks.sql

package db

import (
	"context"
	"database/sql"
)

const createIPBlock = `-- name: CreateIPBlock :one
INSERT INTO ip_blocks (cidr, reason, created_by, created_at, expires_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type CreateIPBlockParams struct {
	Cidr      string        `db:"cidr" json:"cidr"`
	Reason    string        `db:"reason" json:"reason"`
	CreatedBy sql.NullInt64 `db:"created_by" json:"created_by"`
	CreatedAt int64         `db:"created_at" json:"created_at"`
	ExpiresAt sql.NullInt64 `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateIPBlock(ctx context.Context, arg CreateIPBlockParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createIPBlock,
		arg.Cidr,
		arg.Reason,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteExpiredIPBlocks = `-- name: DeleteExpiredIPBlocks :exec
DELETE FROM ip_blocks WHERE expires_at IS NOT NULL AND expires_at <= ?
`

func (q *Queries) DeleteExpiredIPBlocks(ctx context.Context, expiresAt sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredIPBlocks, expiresAt)
	return err
}

const deleteIPBlock = `-- name: DeleteIPBlock :exec
DELETE FROM ip_blocks WHERE id = ?
`

func (q *Queries) DeleteIPBlock(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteIPBlock, id)
	return err
}

const getIPBlock = `-- name: GetIPBlock :one
SELECT id, cidr, reason, created_by, created_at, expires_at FROM ip_blocks WHERE id = ?
`

func (q *Queries) GetIPBlock(ctx context.Context, id int64) (IpBlock, error) {
	row := q.db.QueryRowContext(ctx, getIPBlock, id)
	var i IpBlock
	err := row.Scan(
		&i.ID,
		&i.Cidr,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listActiveIPBlocks = `-- name: ListActiveIPBlocks :many
SELECT b.id, b.cidr, b.reason, b.created_by, u.username AS created_by_username,
       b.created_at, b.expires_at
FROM ip_blocks b
LEFT JOIN users u ON u.id = b.created_by
WHERE b.expires_at IS NULL OR b.expires_at > ?1
ORDER BY b.created_at DESC, b.id DESC
`

type ListActiveIPBlocksRow struct {
	ID                int64          `db:"id" json:"id"`
	Cidr              string         `db:"cidr" json:"cidr"`
	Reason            string         `db:"reason" json:"reason"`
	CreatedBy         sql.NullInt64  `db:"created_by" json:"created_by"`
	CreatedByUsername sql.NullString `db:"created_by_username" json:"created_by_username"`
	CreatedAt         int64          `db:"created_at" json:"created_at"`
	ExpiresAt         sql.NullInt64  `db:"expires_at" json:"expires_at"`
}

// Every block still in force, newest first, with who added it.
func (q *Queries) ListActiveIPBlocks(ctx context.Context, now sql.NullInt64) ([]ListActiveIPBlocksRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveIPBlocks, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveIPBlocksRow{}
	for rows.Next() {
		var i ListActiveIPBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.Cidr,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedByUsername,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
