// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: refresh_tokens.sql

package db

import (
	"context"
)

const countActiveRefreshTokenFamilies = `-- name: CountActiveRefreshTokenFamilies :one
SELECT COUNT(DISTINCT family_id) FROM refresh_tokens WHERE user_id = ? AND revoked = 0 AND expires_at > ?
`

type CountActiveRefreshTokenFamiliesParams struct {
	UserID    int64 `db:"user_id" json:"user_id"`
	ExpiresAt int64 `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CountActiveRefreshTokenFamilies(ctx context.Context, arg CountActiveRefreshTokenFamiliesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveRefreshTokenFamilies, arg.UserID, arg.ExpiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (user_id, token_hash, family_id, expires_at, revoked, created_at)
VALUES (?, ?, ?, ?, 0, ?)
`

type CreateRefreshTokenParams struct {
	UserID    int64  `db:"user_id" json:"user_id"`
	TokenHash string `db:"token_hash" json:"token_hash"`
	FamilyID  string `db:"family_id" json:"family_id"`
	ExpiresAt int64  `db:"expires_at" json:"expires_at"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.FamilyID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens WHERE expires_at < ?
`

// Revoked rows are kept until they expire: they are the tombstones that let
// a replayed, already-rotated token be detected as reuse.
func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredRefreshTokens, expiresAt)
	return err
}

const getOldestActiveRefreshTokenFamily = `-- name: GetOldestActiveRefreshTokenFamily :one
SELECT family_id FROM refresh_tokens WHERE user_id = ? AND revoked = 0 AND expires_at > ? ORDER BY created_at ASC LIMIT 1
`

type GetOldestActiveRefreshTokenFamilyParams struct {
	UserID    int64 `db:"user_id" json:"user_id"`
	ExpiresAt int64 `db:"expires_at" json:"expires_at"`
}

func (q *Queries) GetOldestActiveRefreshTokenFamily(ctx context.Context, arg GetOldestActiveRefreshTokenFamilyParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getOldestActiveRefreshTokenFamily, arg.UserID, arg.ExpiresAt)
	var family_id string
	err := row.Scan(&family_id)
	return family_id, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, family_id, expires_at, revoked, created_at FROM refresh_tokens WHERE token_hash = ?
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :exec
UPDATE refresh_tokens SET revoked = 1 WHERE user_id = ?
`

func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, revokeAllRefreshTokensForUser, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked = 1 WHERE id = ?
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, id)
	return err
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
UPDATE refresh_tokens SET revoked = 1 WHERE family_id = ?
`

func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, familyID string) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshTokenFamily, familyID)
	return err
}
