// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: shared_links.sql

package db

import (
	"context"
	"database/sql"
)

const createSharedLink = `-- name: CreateSharedLink :one
INSERT INTO shared_links (call_id, user_id, token, created_at, expires_at)
VALUES (?, ?, ?, unixepoch(), ?)
ON CONFLICT (call_id) DO UPDATE SET call_id = call_id
RETURNING id, call_id, user_id, token, created_at, expires_at, opens, last_opened_at
`

type CreateSharedLinkParams struct {
	CallID    int64         `db:"call_id" json:"call_id"`
	UserID    int64         `db:"user_id" json:"user_id"`
	Token     string        `db:"token" json:"token"`
	ExpiresAt sql.NullInt64 `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateSharedLink(ctx context.Context, arg CreateSharedLinkParams) (SharedLink, error) {
	row := q.db.QueryRowContext(ctx, createSharedLink,
		arg.CallID,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
	)
	var i SharedLink
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Opens,
		&i.LastOpenedAt,
	)
	return i, err
}

const deleteSharedLink = `-- name: DeleteSharedLink :exec
DELETE FROM shared_links WHERE id = ?
`

func (q *Queries) DeleteSharedLink(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSharedLink, id)
	return err
}

const deleteSharedLinkByCallID = `-- name: DeleteSharedLinkByCallID :exec
DELETE FROM shared_links WHERE call_id = ?
`

func (q *Queries) DeleteSharedLinkByCallID(ctx context.Context, callID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSharedLinkByCallID, callID)
	return err
}

const getSharedLinkByCallID = `-- name: GetSharedLinkByCallID :one
SELECT id, call_id, user_id, token, created_at, expires_at, opens, last_opened_at FROM shared_links WHERE call_id = ? LIMIT 1
`

func (q *Queries) GetSharedLinkByCallID(ctx context.Context, callID int64) (SharedLink, error) {
	row := q.db.QueryRowContext(ctx, getSharedLinkByCallID, callID)
	var i SharedLink
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Opens,
		&i.LastOpenedAt,
	)
	return i, err
}

const getSharedLinkByToken = `-- name: GetSharedLinkByToken :one
SELECT
    sl.id, sl.call_id, sl.user_id, sl.token, sl.created_at, sl.expires_at, sl.opens, sl.last_opened_at,
    c.audio_path,
    c.audio_name,
    c.audio_type,
    c.date_time,
    c.frequency,
    c.duration,
    c.source,
    c.site,
    c.channel,
    c.decoder,
    s.label  AS system_label,
    t.label  AS talkgroup_label,
    t.name   AS talkgroup_name
FROM shared_links sl
JOIN calls      c ON c.id = sl.call_id
LEFT JOIN systems    s ON s.id = c.system_id
LEFT JOIN talkgroups t ON t.id = c.talkgroup_id
WHERE sl.token = ?
LIMIT 1
`

type GetSharedLinkByTokenRow struct {
	ID             int64          `db:"id" json:"id"`
	CallID         int64          `db:"call_id" json:"call_id"`
	UserID         int64          `db:"user_id" json:"user_id"`
	Token          string         `db:"token" json:"token"`
	CreatedAt      int64          `db:"created_at" json:"created_at"`
	ExpiresAt      sql.NullInt64  `db:"expires_at" json:"expires_at"`
	Opens          int64          `db:"opens" json:"opens"`
	LastOpenedAt   sql.NullInt64  `db:"last_opened_at" json:"last_opened_at"`
	AudioPath      string         `db:"audio_path" json:"audio_path"`
	AudioName      string         `db:"audio_name" json:"audio_name"`
	AudioType      string         `db:"audio_type" json:"audio_type"`
	DateTime       int64          `db:"date_time" json:"date_time"`
	Frequency      sql.NullInt64  `db:"frequency" json:"frequency"`
	Duration       sql.NullInt64  `db:"duration" json:"duration"`
	Source         sql.NullInt64  `db:"source" json:"source"`
	Site           sql.NullString `db:"site" json:"site"`
	Channel        sql.NullString `db:"channel" json:"channel"`
	Decoder        sql.NullString `db:"decoder" json:"decoder"`
	SystemLabel    sql.NullString `db:"system_label" json:"system_label"`
	TalkgroupLabel sql.NullString `db:"talkgroup_label" json:"talkgroup_label"`
	TalkgroupName  sql.NullString `db:"talkgroup_name" json:"talkgroup_name"`
}

func (q *Queries) GetSharedLinkByToken(ctx context.Context, token string) (GetSharedLinkByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getSharedLinkByToken, token)
	var i GetSharedLinkByTokenRow
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Opens,
		&i.LastOpenedAt,
		&i.AudioPath,
		&i.AudioName,
		&i.AudioType,
		&i.DateTime,
		&i.Frequency,
		&i.Duration,
		&i.Source,
		&i.Site,
		&i.Channel,
		&i.Decoder,
		&i.SystemLabel,
		&i.TalkgroupLabel,
		&i.TalkgroupName,
	)
	return i, err
}

const listSharedLinks = `-- name: ListSharedLinks :many
SELECT
    sl.id,
    sl.call_id,
    sl.user_id,
    sl.token,
    sl.created_at,
    sl.expires_at,
    sl.opens,
    sl.last_opened_at,
    u.username   AS shared_by,
    c.date_time,
    c.duration,
    s.label      AS system_label,
    t.label      AS talkgroup_label,
    t.name       AS talkgroup_name
FROM shared_links sl
JOIN users       u ON u.id = sl.user_id
JOIN calls       c ON c.id = sl.call_id
LEFT JOIN systems    s ON s.id = c.system_id
LEFT JOIN talkgroups t ON t.id = c.talkgroup_id
ORDER BY sl.created_at DESC
`

type ListSharedLinksRow struct {
	ID             int64          `db:"id" json:"id"`
	CallID         int64          `db:"call_id" json:"call_id"`
	UserID         int64          `db:"user_id" json:"user_id"`
	Token          string         `db:"token" json:"token"`
	CreatedAt      int64          `db:"created_at" json:"created_at"`
	ExpiresAt      sql.NullInt64  `db:"expires_at" json:"expires_at"`
	Opens          int64          `db:"opens" json:"opens"`
	LastOpenedAt   sql.NullInt64  `db:"last_opened_at" json:"last_opened_at"`
	SharedBy       string         `db:"shared_by" json:"shared_by"`
	DateTime       int64          `db:"date_time" json:"date_time"`
	Duration       sql.NullInt64  `db:"duration" json:"duration"`
	SystemLabel    sql.NullString `db:"system_label" json:"system_label"`
	TalkgroupLabel sql.NullString `db:"talkgroup_label" json:"talkgroup_label"`
	TalkgroupName  sql.NullString `db:"talkgroup_name" json:"talkgroup_name"`
}

func (q *Queries) ListSharedLinks(ctx context.Context) ([]ListSharedLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listSharedLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharedLinksRow{}
	for rows.Next() {
		var i ListSharedLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.UserID,
			&i.Token,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Opens,
			&i.LastOpenedAt,
			&i.SharedBy,
			&i.DateTime,
			&i.Duration,
			&i.SystemLabel,
			&i.TalkgroupLabel,
			&i.TalkgroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreSharedLink = `-- name: RestoreSharedLink :exec
INSERT INTO shared_links (call_id, user_id, token, created_at, expires_at)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type RestoreSharedLinkParams struct {
	CallID    int64         `db:"call_id" json:"call_id"`
	UserID    int64         `db:"user_id" json:"user_id"`
	Token     string        `db:"token" json:"token"`
	CreatedAt int64         `db:"created_at" json:"created_at"`
	ExpiresAt sql.NullInt64 `db:"expires_at" json:"expires_at"`
}

func (q *Queries) RestoreSharedLink(ctx context.Context, arg RestoreSharedLinkParams) error {
	_, err := q.db.ExecContext(ctx, restoreSharedLink,
		arg.CallID,
		arg.UserID,
		arg.Token,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const touchSharedLinkOpened = `-- name: TouchSharedLinkOpened :exec
UPDATE shared_links SET opens = opens + 1, last_opened_at = ?1 WHERE id = ?2
`

type TouchSharedLinkOpenedParams struct {
	Now sql.NullInt64 `db:"now" json:"now"`
	ID  int64         `db:"id" json:"id"`
}

func (q *Queries) TouchSharedLinkOpened(ctx context.Context, arg TouchSharedLinkOpenedParams) error {
	_, err := q.db.ExecContext(ctx, touchSharedLinkOpened, arg.Now, arg.ID)
	return err
}
