// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: systems.sql

package db

import (
	"context"
	"database/sql"
)

const countTalkgroupsPerSystem = `-- name: CountTalkgroupsPerSystem :many
SELECT system_id, COUNT(*) AS talkgroups FROM talkgroups GROUP BY system_id
`

type CountTalkgroupsPerSystemRow struct {
	SystemID   int64 `db:"system_id" json:"system_id"`
	Talkgroups int64 `db:"talkgroups" json:"talkgroups"`
}

func (q *Queries) CountTalkgroupsPerSystem(ctx context.Context) ([]CountTalkgroupsPerSystemRow, error) {
	rows, err := q.db.QueryContext(ctx, countTalkgroupsPerSystem)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountTalkgroupsPerSystemRow{}
	for rows.Next() {
		var i CountTalkgroupsPerSystemRow
		if err := rows.Scan(&i.SystemID, &i.Talkgroups); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUnitsPerSystem = `-- name: CountUnitsPerSystem :many
SELECT system_id, COUNT(*) AS units FROM units GROUP BY system_id
`

type CountUnitsPerSystemRow struct {
	SystemID int64 `db:"system_id" json:"system_id"`
	Units    int64 `db:"units" json:"units"`
}

func (q *Queries) CountUnitsPerSystem(ctx context.Context) ([]CountUnitsPerSystemRow, error) {
	rows, err := q.db.QueryContext(ctx, countUnitsPerSystem)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountUnitsPerSystemRow{}
	for rows.Next() {
		var i CountUnitsPerSystemRow
		if err := rows.Scan(&i.SystemID, &i.Units); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSystem = `-- name: CreateSystem :one
INSERT INTO systems (
    system_id,
    label,
    auto_populate_talkgroups,
    blacklists_json,
    led,
    "order"
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
) RETURNING id
`

type CreateSystemParams struct {
	SystemID               int64          `db:"system_id" json:"system_id"`
	Label                  string         `db:"label" json:"label"`
	AutoPopulateTalkgroups int64          `db:"auto_populate_talkgroups" json:"auto_populate_talkgroups"`
	BlacklistsJson         sql.NullString `db:"blacklists_json" json:"blacklists_json"`
	Led                    sql.NullString `db:"led" json:"led"`
	Order                  int64          `db:"order" json:"order"`
}

func (q *Queries) CreateSystem(ctx context.Context, arg CreateSystemParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createSystem,
		arg.SystemID,
		arg.Label,
		arg.AutoPopulateTalkgroups,
		arg.BlacklistsJson,
		arg.Led,
		arg.Order,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteSystem = `-- name: DeleteSystem :exec
DELETE FROM systems WHERE id = ?
`

func (q *Queries) DeleteSystem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSystem, id)
	return err
}

const getSystem = `-- name: GetSystem :one
SELECT id, system_id, label, auto_populate_talkgroups, blacklists_json, led, "order" FROM systems WHERE id = ? LIMIT 1
`

func (q *Queries) GetSystem(ctx context.Context, id int64) (System, error) {
	row := q.db.QueryRowContext(ctx, getSystem, id)
	var i System
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.Label,
		&i.AutoPopulateTalkgroups,
		&i.BlacklistsJson,
		&i.Led,
		&i.Order,
	)
	return i, err
}

const getSystemByLabel = `-- name: GetSystemByLabel :one
SELECT id, system_id, label, auto_populate_talkgroups, blacklists_json, led, "order" FROM systems WHERE label = ? LIMIT 1
`

func (q *Queries) GetSystemByLabel(ctx context.Context, label string) (System, error) {
	row := q.db.QueryRowContext(ctx, getSystemByLabel, label)
	var i System
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.Label,
		&i.AutoPopulateTalkgroups,
		&i.BlacklistsJson,
		&i.Led,
		&i.Order,
	)
	return i, err
}

const getSystemBySystemID = `-- name: GetSystemBySystemID :one
SELECT id, system_id, label, auto_populate_talkgroups, blacklists_json, led, "order" FROM systems WHERE system_id = ? LIMIT 1
`

func (q *Queries) GetSystemBySystemID(ctx context.Context, systemID int64) (System, error) {
	row := q.db.QueryRowContext(ctx, getSystemBySystemID, systemID)
	var i System
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.Label,
		&i.AutoPopulateTalkgroups,
		&i.BlacklistsJson,
		&i.Led,
		&i.Order,
	)
	return i, err
}

const listSystems = `-- name: ListSystems :many
SELECT id, system_id, label, auto_populate_talkgroups, blacklists_json, led, "order" FROM systems ORDER BY "order" ASC, id ASC
`

func (q *Queries) ListSystems(ctx context.Context) ([]System, error) {
	rows, err := q.db.QueryContext(ctx, listSystems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []System{}
	for rows.Next() {
		var i System
		if err := rows.Scan(
			&i.ID,
			&i.SystemID,
			&i.Label,
			&i.AutoPopulateTalkgroups,
			&i.BlacklistsJson,
			&i.Led,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSystem = `-- name: UpdateSystem :exec
UPDATE systems SET
    system_id                = ?1,
    label                    = ?2,
    auto_populate_talkgroups = ?3,
    blacklists_json          = ?4,
    led                      = ?5,
    "order"                  = ?6
WHERE id = ?7
`

type UpdateSystemParams struct {
	SystemID               int64          `db:"system_id" json:"system_id"`
	Label                  string         `db:"label" json:"label"`
	AutoPopulateTalkgroups int64          `db:"auto_populate_talkgroups" json:"auto_populate_talkgroups"`
	BlacklistsJson         sql.NullString `db:"blacklists_json" json:"blacklists_json"`
	Led                    sql.NullString `db:"led" json:"led"`
	Order                  int64          `db:"order" json:"order"`
	ID                     int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateSystem(ctx context.Context, arg UpdateSystemParams) error {
	_, err := q.db.ExecContext(ctx, updateSystem,
		arg.SystemID,
		arg.Label,
		arg.AutoPopulateTalkgroups,
		arg.BlacklistsJson,
		arg.Led,
		arg.Order,
		arg.ID,
	)
	return err
}

const updateSystemBlacklists = `-- name: UpdateSystemBlacklists :exec
UPDATE systems SET blacklists_json = ? WHERE id = ?
`

type UpdateSystemBlacklistsParams struct {
	BlacklistsJson sql.NullString `db:"blacklists_json" json:"blacklists_json"`
	ID             int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateSystemBlacklists(ctx context.Context, arg UpdateSystemBlacklistsParams) error {
	_, err := q.db.ExecContext(ctx, updateSystemBlacklists, arg.BlacklistsJson, arg.ID)
	return err
}

const updateSystemOrder = `-- name: UpdateSystemOrder :exec
UPDATE systems SET "order" = ? WHERE id = ?
`

type UpdateSystemOrderParams struct {
	Order int64 `db:"order" json:"order"`
	ID    int64 `db:"id" json:"id"`
}

func (q *Queries) UpdateSystemOrder(ctx context.Context, arg UpdateSystemOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateSystemOrder, arg.Order, arg.ID)
	return err
}
