// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tags.sql

package db

import (
	"context"
	"database/sql"
)

const countTalkgroupsWithTag = `-- name: CountTalkgroupsWithTag :one
SELECT COUNT(*) FROM talkgroups WHERE tag_id = ?
`

func (q *Queries) CountTalkgroupsWithTag(ctx context.Context, tagID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTalkgroupsWithTag, tagID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (label) VALUES (?1) RETURNING id
`

func (q *Queries) CreateTag(ctx context.Context, label string) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTag, label)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const getTag = `-- name: GetTag :one
SELECT id, label FROM tags WHERE id = ? LIMIT 1
`

func (q *Queries) GetTag(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(&i.ID, &i.Label)
	return i, err
}

const getTagByLabel = `-- name: GetTagByLabel :one
SELECT id, label FROM tags WHERE label = ? LIMIT 1
`

func (q *Queries) GetTagByLabel(ctx context.Context, label string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByLabel, label)
	var i Tag
	err := row.Scan(&i.ID, &i.Label)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, label FROM tags ORDER BY label ASC
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsWithUsage = `-- name: ListTagsWithUsage :many
SELECT tg.id, tg.label, COUNT(t.id) AS talkgroups
FROM tags tg
LEFT JOIN talkgroups t ON t.tag_id = tg.id
GROUP BY tg.id
ORDER BY tg.label ASC
`

type ListTagsWithUsageRow struct {
	ID         int64  `db:"id" json:"id"`
	Label      string `db:"label" json:"label"`
	Talkgroups int64  `db:"talkgroups" json:"talkgroups"`
}

func (q *Queries) ListTagsWithUsage(ctx context.Context) ([]ListTagsWithUsageRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagsWithUsage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsWithUsageRow{}
	for rows.Next() {
		var i ListTagsWithUsageRow
		if err := rows.Scan(&i.ID, &i.Label, &i.Talkgroups); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveTalkgroupsToTag = `-- name: MoveTalkgroupsToTag :exec
UPDATE talkgroups SET tag_id = ?1 WHERE tag_id = ?2
`

type MoveTalkgroupsToTagParams struct {
	ToTag   sql.NullInt64 `db:"to_tag" json:"to_tag"`
	FromTag sql.NullInt64 `db:"from_tag" json:"from_tag"`
}

func (q *Queries) MoveTalkgroupsToTag(ctx context.Context, arg MoveTalkgroupsToTagParams) error {
	_, err := q.db.ExecContext(ctx, moveTalkgroupsToTag, arg.ToTag, arg.FromTag)
	return err
}

const updateTag = `-- name: UpdateTag :exec
UPDATE tags SET label = ?1 WHERE id = ?2
`

type UpdateTagParams struct {
	Label string `db:"label" json:"label"`
	ID    int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) error {
	_, err := q.db.ExecContext(ctx, updateTag, arg.Label, arg.ID)
	return err
}
