// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: talkgroups.sql

package db

import (
	"context"
	"database/sql"
)

const createTalkgroup = `-- name: CreateTalkgroup :one
INSERT INTO talkgroups (
    system_id,
    talkgroup_id,
    label,
    name,
    frequency,
    led,
    group_id,
    tag_id,
    "order"
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9
) RETURNING id
`

type CreateTalkgroupParams struct {
	SystemID    int64          `db:"system_id" json:"system_id"`
	TalkgroupID int64          `db:"talkgroup_id" json:"talkgroup_id"`
	Label       sql.NullString `db:"label" json:"label"`
	Name        sql.NullString `db:"name" json:"name"`
	Frequency   sql.NullInt64  `db:"frequency" json:"frequency"`
	Led         sql.NullString `db:"led" json:"led"`
	GroupID     sql.NullInt64  `db:"group_id" json:"group_id"`
	TagID       sql.NullInt64  `db:"tag_id" json:"tag_id"`
	Order       int64          `db:"order" json:"order"`
}

func (q *Queries) CreateTalkgroup(ctx context.Context, arg CreateTalkgroupParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTalkgroup,
		arg.SystemID,
		arg.TalkgroupID,
		arg.Label,
		arg.Name,
		arg.Frequency,
		arg.Led,
		arg.GroupID,
		arg.TagID,
		arg.Order,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteTalkgroup = `-- name: DeleteTalkgroup :exec
DELETE FROM talkgroups WHERE id = ?
`

func (q *Queries) DeleteTalkgroup(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTalkgroup, id)
	return err
}

const getTalkgroup = `-- name: GetTalkgroup :one
SELECT id, system_id, talkgroup_id, label, name, frequency, led, group_id, tag_id, "order" FROM talkgroups WHERE id = ? LIMIT 1
`

func (q *Queries) GetTalkgroup(ctx context.Context, id int64) (Talkgroup, error) {
	row := q.db.QueryRowContext(ctx, getTalkgroup, id)
	var i Talkgroup
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.TalkgroupID,
		&i.Label,
		&i.Name,
		&i.Frequency,
		&i.Led,
		&i.GroupID,
		&i.TagID,
		&i.Order,
	)
	return i, err
}

const getTalkgroupBySystemAndTGID = `-- name: GetTalkgroupBySystemAndTGID :one
SELECT id, system_id, talkgroup_id, label, name, frequency, led, group_id, tag_id, "order" FROM talkgroups
WHERE system_id = ? AND talkgroup_id = ?
LIMIT 1
`

type GetTalkgroupBySystemAndTGIDParams struct {
	SystemID    int64 `db:"system_id" json:"system_id"`
	TalkgroupID int64 `db:"talkgroup_id" json:"talkgroup_id"`
}

func (q *Queries) GetTalkgroupBySystemAndTGID(ctx context.Context, arg GetTalkgroupBySystemAndTGIDParams) (Talkgroup, error) {
	row := q.db.QueryRowContext(ctx, getTalkgroupBySystemAndTGID, arg.SystemID, arg.TalkgroupID)
	var i Talkgroup
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.TalkgroupID,
		&i.Label,
		&i.Name,
		&i.Frequency,
		&i.Led,
		&i.GroupID,
		&i.TagID,
		&i.Order,
	)
	return i, err
}

const listAllTalkgroups = `-- name: ListAllTalkgroups :many
SELECT id, system_id, talkgroup_id, label, name, frequency, led, group_id, tag_id, "order" FROM talkgroups ORDER BY system_id ASC, "order" ASC, talkgroup_id ASC
`

func (q *Queries) ListAllTalkgroups(ctx context.Context) ([]Talkgroup, error) {
	rows, err := q.db.QueryContext(ctx, listAllTalkgroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Talkgroup{}
	for rows.Next() {
		var i Talkgroup
		if err := rows.Scan(
			&i.ID,
			&i.SystemID,
			&i.TalkgroupID,
			&i.Label,
			&i.Name,
			&i.Frequency,
			&i.Led,
			&i.GroupID,
			&i.TagID,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTalkgroupsBySystem = `-- name: ListTalkgroupsBySystem :many
SELECT id, system_id, talkgroup_id, label, name, frequency, led, group_id, tag_id, "order" FROM talkgroups
WHERE system_id = ?
ORDER BY "order" ASC, talkgroup_id ASC
`

func (q *Queries) ListTalkgroupsBySystem(ctx context.Context, systemID int64) ([]Talkgroup, error) {
	rows, err := q.db.QueryContext(ctx, listTalkgroupsBySystem, systemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Talkgroup{}
	for rows.Next() {
		var i Talkgroup
		if err := rows.Scan(
			&i.ID,
			&i.SystemID,
			&i.TalkgroupID,
			&i.Label,
			&i.Name,
			&i.Frequency,
			&i.Led,
			&i.GroupID,
			&i.TagID,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTalkgroupGroup = `-- name: SetTalkgroupGroup :exec
UPDATE talkgroups SET group_id = ? WHERE id = ?
`

type SetTalkgroupGroupParams struct {
	GroupID sql.NullInt64 `db:"group_id" json:"group_id"`
	ID      int64         `db:"id" json:"id"`
}

func (q *Queries) SetTalkgroupGroup(ctx context.Context, arg SetTalkgroupGroupParams) error {
	_, err := q.db.ExecContext(ctx, setTalkgroupGroup, arg.GroupID, arg.ID)
	return err
}

const setTalkgroupLed = `-- name: SetTalkgroupLed :exec
UPDATE talkgroups SET led = ? WHERE id = ?
`

type SetTalkgroupLedParams struct {
	Led sql.NullString `db:"led" json:"led"`
	ID  int64          `db:"id" json:"id"`
}

func (q *Queries) SetTalkgroupLed(ctx context.Context, arg SetTalkgroupLedParams) error {
	_, err := q.db.ExecContext(ctx, setTalkgroupLed, arg.Led, arg.ID)
	return err
}

const setTalkgroupTag = `-- name: SetTalkgroupTag :exec
UPDATE talkgroups SET tag_id = ? WHERE id = ?
`

type SetTalkgroupTagParams struct {
	TagID sql.NullInt64 `db:"tag_id" json:"tag_id"`
	ID    int64         `db:"id" json:"id"`
}

func (q *Queries) SetTalkgroupTag(ctx context.Context, arg SetTalkgroupTagParams) error {
	_, err := q.db.ExecContext(ctx, setTalkgroupTag, arg.TagID, arg.ID)
	return err
}

const updateTalkgroup = `-- name: UpdateTalkgroup :exec
UPDATE talkgroups SET
    talkgroup_id = ?1,
    label        = ?2,
    name         = ?3,
    frequency    = ?4,
    led          = ?5,
    group_id     = ?6,
    tag_id       = ?7,
    "order"      = ?8
WHERE id = ?9
`

type UpdateTalkgroupParams struct {
	TalkgroupID int64          `db:"talkgroup_id" json:"talkgroup_id"`
	Label       sql.NullString `db:"label" json:"label"`
	Name        sql.NullString `db:"name" json:"name"`
	Frequency   sql.NullInt64  `db:"frequency" json:"frequency"`
	Led         sql.NullString `db:"led" json:"led"`
	GroupID     sql.NullInt64  `db:"group_id" json:"group_id"`
	TagID       sql.NullInt64  `db:"tag_id" json:"tag_id"`
	Order       int64          `db:"order" json:"order"`
	ID          int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateTalkgroup(ctx context.Context, arg UpdateTalkgroupParams) error {
	_, err := q.db.ExecContext(ctx, updateTalkgroup,
		arg.TalkgroupID,
		arg.Label,
		arg.Name,
		arg.Frequency,
		arg.Led,
		arg.GroupID,
		arg.TagID,
		arg.Order,
		arg.ID,
	)
	return err
}

const upsertTalkgroup = `-- name: UpsertTalkgroup :exec
INSERT INTO talkgroups (system_id, talkgroup_id, label, name, frequency, led, group_id, tag_id, "order")
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
ON CONFLICT (system_id, talkgroup_id) DO UPDATE SET
    label     = excluded.label,
    name      = excluded.name,
    frequency = excluded.frequency,
    led       = excluded.led,
    group_id  = excluded.group_id,
    tag_id    = excluded.tag_id,
    "order"   = excluded."order"
`

type UpsertTalkgroupParams struct {
	SystemID    int64          `db:"system_id" json:"system_id"`
	TalkgroupID int64          `db:"talkgroup_id" json:"talkgroup_id"`
	Label       sql.NullString `db:"label" json:"label"`
	Name        sql.NullString `db:"name" json:"name"`
	Frequency   sql.NullInt64  `db:"frequency" json:"frequency"`
	Led         sql.NullString `db:"led" json:"led"`
	GroupID     sql.NullInt64  `db:"group_id" json:"group_id"`
	TagID       sql.NullInt64  `db:"tag_id" json:"tag_id"`
	Order       int64          `db:"order" json:"order"`
}

func (q *Queries) UpsertTalkgroup(ctx context.Context, arg UpsertTalkgroupParams) error {
	_, err := q.db.ExecContext(ctx, upsertTalkgroup,
		arg.SystemID,
		arg.TalkgroupID,
		arg.Label,
		arg.Name,
		arg.Frequency,
		arg.Led,
		arg.GroupID,
		arg.TagID,
		arg.Order,
	)
	return err
}
