// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transcription_jobs.sql

package db

import (
	"context"
	"database/sql"
)

const countTranscriptionJobs = `-- name: CountTranscriptionJobs :one
SELECT
    CAST(SUM(CASE WHEN status = 'queued' THEN 1 ELSE 0 END) AS INTEGER) AS queued,
    CAST(SUM(CASE WHEN status = 'failed' AND finished_at >= ?1 THEN 1 ELSE 0 END) AS INTEGER) AS failed_recent,
    CAST(SUM(CASE WHEN status = 'skipped' AND finished_at >= ?1 THEN 1 ELSE 0 END) AS INTEGER) AS skipped_recent
FROM transcription_jobs
`

type CountTranscriptionJobsRow struct {
	Queued        int64 `db:"queued" json:"queued"`
	FailedRecent  int64 `db:"failed_recent" json:"failed_recent"`
	SkippedRecent int64 `db:"skipped_recent" json:"skipped_recent"`
}

func (q *Queries) CountTranscriptionJobs(ctx context.Context, since sql.NullInt64) (CountTranscriptionJobsRow, error) {
	row := q.db.QueryRowContext(ctx, countTranscriptionJobs, since)
	var i CountTranscriptionJobsRow
	err := row.Scan(&i.Queued, &i.FailedRecent, &i.SkippedRecent)
	return i, err
}

const deleteTranscriptionJobsBefore = `-- name: DeleteTranscriptionJobsBefore :execrows
DELETE FROM transcription_jobs WHERE status <> 'queued' AND created_at < ?
`

func (q *Queries) DeleteTranscriptionJobsBefore(ctx context.Context, createdAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTranscriptionJobsBefore, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishTranscriptionJob = `-- name: FinishTranscriptionJob :exec
UPDATE transcription_jobs
SET status = ?1, error = ?2, duration_ms = ?3, finished_at = ?4
WHERE call_id = ?5
`

type FinishTranscriptionJobParams struct {
	Status     string         `db:"status" json:"status"`
	Error      sql.NullString `db:"error" json:"error"`
	DurationMs sql.NullInt64  `db:"duration_ms" json:"duration_ms"`
	FinishedAt sql.NullInt64  `db:"finished_at" json:"finished_at"`
	CallID     int64          `db:"call_id" json:"call_id"`
}

func (q *Queries) FinishTranscriptionJob(ctx context.Context, arg FinishTranscriptionJobParams) error {
	_, err := q.db.ExecContext(ctx, finishTranscriptionJob,
		arg.Status,
		arg.Error,
		arg.DurationMs,
		arg.FinishedAt,
		arg.CallID,
	)
	return err
}

const getTranscriptionJob = `-- name: GetTranscriptionJob :one
SELECT id, call_id, status, error, model, duration_ms, created_at, finished_at FROM transcription_jobs WHERE call_id = ? LIMIT 1
`

func (q *Queries) GetTranscriptionJob(ctx context.Context, callID int64) (TranscriptionJob, error) {
	row := q.db.QueryRowContext(ctx, getTranscriptionJob, callID)
	var i TranscriptionJob
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.Status,
		&i.Error,
		&i.Model,
		&i.DurationMs,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listTranscriptionJobs = `-- name: ListTranscriptionJobs :many
SELECT
    j.call_id, j.status, j.error, j.model, j.duration_ms, j.created_at, j.finished_at,
    c.date_time AS call_time,
    CAST(COALESCE(c.duration, 0) AS INTEGER) AS call_duration_ms,
    s.label AS system_label,
    t.talkgroup_id AS talkgroup_number,
    t.label AS talkgroup_label
FROM transcription_jobs j
JOIN calls c ON c.id = j.call_id
JOIN systems s ON s.id = c.system_id
LEFT JOIN talkgroups t ON t.id = c.talkgroup_id
WHERE (?1 = '' OR j.status = ?1)
ORDER BY j.created_at DESC, j.id DESC
LIMIT ?2
`

type ListTranscriptionJobsParams struct {
	Status interface{} `db:"status" json:"status"`
	Limit  int64       `db:"limit" json:"limit"`
}

type ListTranscriptionJobsRow struct {
	CallID          int64          `db:"call_id" json:"call_id"`
	Status          string         `db:"status" json:"status"`
	Error           sql.NullString `db:"error" json:"error"`
	Model           sql.NullString `db:"model" json:"model"`
	DurationMs      sql.NullInt64  `db:"duration_ms" json:"duration_ms"`
	CreatedAt       int64          `db:"created_at" json:"created_at"`
	FinishedAt      sql.NullInt64  `db:"finished_at" json:"finished_at"`
	CallTime        int64          `db:"call_time" json:"call_time"`
	CallDurationMs  int64          `db:"call_duration_ms" json:"call_duration_ms"`
	SystemLabel     string         `db:"system_label" json:"system_label"`
	TalkgroupNumber sql.NullInt64  `db:"talkgroup_number" json:"talkgroup_number"`
	TalkgroupLabel  sql.NullString `db:"talkgroup_label" json:"talkgroup_label"`
}

// Recent jobs with the call they belong to; an empty status lists them all.
func (q *Queries) ListTranscriptionJobs(ctx context.Context, arg ListTranscriptionJobsParams) ([]ListTranscriptionJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTranscriptionJobs, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTranscriptionJobsRow{}
	for rows.Next() {
		var i ListTranscriptionJobsRow
		if err := rows.Scan(
			&i.CallID,
			&i.Status,
			&i.Error,
			&i.Model,
			&i.DurationMs,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.CallTime,
			&i.CallDurationMs,
			&i.SystemLabel,
			&i.TalkgroupNumber,
			&i.TalkgroupLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTranscriptionJob = `-- name: UpsertTranscriptionJob :exec
INSERT INTO transcription_jobs (call_id, status, error, model, duration_ms, created_at, finished_at)
VALUES (?1, ?2, ?3, ?4, NULL, ?5, CASE WHEN ?2 = 'queued' THEN NULL ELSE ?5 END)
ON CONFLICT(call_id) DO UPDATE SET
    status = excluded.status,
    error = excluded.error,
    model = excluded.model,
    duration_ms = NULL,
    created_at = excluded.created_at,
    finished_at = excluded.finished_at
`

type UpsertTranscriptionJobParams struct {
	CallID    int64          `db:"call_id" json:"call_id"`
	Status    string         `db:"status" json:"status"`
	Error     sql.NullString `db:"error" json:"error"`
	Model     sql.NullString `db:"model" json:"model"`
	CreatedAt int64          `db:"created_at" json:"created_at"`
}

// A call handed to the transcriber (again): back to queued with a clean slate.
func (q *Queries) UpsertTranscriptionJob(ctx context.Context, arg UpsertTranscriptionJobParams) error {
	_, err := q.db.ExecContext(ctx, upsertTranscriptionJob,
		arg.CallID,
		arg.Status,
		arg.Error,
		arg.Model,
		arg.CreatedAt,
	)
	return err
}
