// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    password_hash,
    role,
    disabled,
    systems_json,
    expiration,
    "limit",
    password_need_change,
    created_at,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10
) RETURNING id
`

type CreateUserParams struct {
	Username           string         `db:"username" json:"username"`
	PasswordHash       string         `db:"password_hash" json:"-"`
	Role               string         `db:"role" json:"role"`
	Disabled           int64          `db:"disabled" json:"disabled"`
	SystemsJson        sql.NullString `db:"systems_json" json:"systems_json"`
	Expiration         sql.NullInt64  `db:"expiration" json:"expiration"`
	Limit              sql.NullInt64  `db:"limit" json:"limit"`
	PasswordNeedChange int64          `db:"password_need_change" json:"password_need_change"`
	CreatedAt          int64          `db:"created_at" json:"created_at"`
	UpdatedAt          int64          `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.Disabled,
		arg.SystemsJson,
		arg.Expiration,
		arg.Limit,
		arg.PasswordNeedChange,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, password_hash, role, disabled, systems_json, expiration, "limit", password_need_change, tg_selection_json, preferences_json, created_at, updated_at FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Disabled,
		&i.SystemsJson,
		&i.Expiration,
		&i.Limit,
		&i.PasswordNeedChange,
		&i.TgSelectionJson,
		&i.PreferencesJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, role, disabled, systems_json, expiration, "limit", password_need_change, tg_selection_json, preferences_json, created_at, updated_at FROM users WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Disabled,
		&i.SystemsJson,
		&i.Expiration,
		&i.Limit,
		&i.PasswordNeedChange,
		&i.TgSelectionJson,
		&i.PreferencesJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, role, disabled, systems_json, expiration, "limit", password_need_change, tg_selection_json, preferences_json, created_at, updated_at FROM users ORDER BY id ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Role,
			&i.Disabled,
			&i.SystemsJson,
			&i.Expiration,
			&i.Limit,
			&i.PasswordNeedChange,
			&i.TgSelectionJson,
			&i.PreferencesJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET
    username     = ?1,
    role         = ?2,
    disabled     = ?3,
    systems_json = ?4,
    expiration   = ?5,
    "limit"      = ?6,
    updated_at   = ?7
WHERE id = ?8
`

type UpdateUserParams struct {
	Username    string         `db:"username" json:"username"`
	Role        string         `db:"role" json:"role"`
	Disabled    int64          `db:"disabled" json:"disabled"`
	SystemsJson sql.NullString `db:"systems_json" json:"systems_json"`
	Expiration  sql.NullInt64  `db:"expiration" json:"expiration"`
	Limit       sql.NullInt64  `db:"limit" json:"limit"`
	UpdatedAt   int64          `db:"updated_at" json:"updated_at"`
	ID          int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Username,
		arg.Role,
		arg.Disabled,
		arg.SystemsJson,
		arg.Expiration,
		arg.Limit,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET
    password_hash        = ?1,
    password_need_change = 0,
    updated_at           = ?2
WHERE id = ?3
`

type UpdateUserPasswordParams struct {
	PasswordHash string `db:"password_hash" json:"-"`
	UpdatedAt    int64  `db:"updated_at" json:"updated_at"`
	ID           int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :exec
UPDATE users SET
    preferences_json = ?1,
    updated_at       = ?2
WHERE id = ?3
`

type UpdateUserPreferencesParams struct {
	PreferencesJson sql.NullString `db:"preferences_json" json:"preferences_json"`
	UpdatedAt       int64          `db:"updated_at" json:"updated_at"`
	ID              int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPreferences, arg.PreferencesJson, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserTGSelection = `-- name: UpdateUserTGSelection :exec
UPDATE users SET
    tg_selection_json = ?1,
    updated_at        = ?2
WHERE id = ?3
`

type UpdateUserTGSelectionParams struct {
	TgSelectionJson sql.NullString `db:"tg_selection_json" json:"tg_selection_json"`
	UpdatedAt       int64          `db:"updated_at" json:"updated_at"`
	ID              int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateUserTGSelection(ctx context.Context, arg UpdateUserTGSelectionParams) error {
	_, err := q.db.ExecContext(ctx, updateUserTGSelection, arg.TgSelectionJson, arg.UpdatedAt, arg.ID)
	return err
}
