// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: webhooks.sql

package db

import (
	"context"
	"database/sql"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (
    url,
    type,
    secret,
    systems_json,
    disabled,
    "order",
    label
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7
) RETURNING id
`

type CreateWebhookParams struct {
	Url         string         `db:"url" json:"url"`
	Type        string         `db:"type" json:"type"`
	Secret      sql.NullString `db:"secret" json:"secret"`
	SystemsJson sql.NullString `db:"systems_json" json:"systems_json"`
	Disabled    int64          `db:"disabled" json:"disabled"`
	Order       int64          `db:"order" json:"order"`
	Label       string         `db:"label" json:"label"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createWebhook,
		arg.Url,
		arg.Type,
		arg.Secret,
		arg.SystemsJson,
		arg.Disabled,
		arg.Order,
		arg.Label,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks WHERE id = ?
`

func (q *Queries) DeleteWebhook(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWebhook, id)
	return err
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, url, type, secret, systems_json, disabled, "order", label, last_at, last_ok, last_status, last_error, last_ok_at FROM webhooks WHERE id = ? LIMIT 1
`

func (q *Queries) GetWebhook(ctx context.Context, id int64) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, getWebhook, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Type,
		&i.Secret,
		&i.SystemsJson,
		&i.Disabled,
		&i.Order,
		&i.Label,
		&i.LastAt,
		&i.LastOk,
		&i.LastStatus,
		&i.LastError,
		&i.LastOkAt,
	)
	return i, err
}

const listActiveWebhooks = `-- name: ListActiveWebhooks :many
SELECT id, url, type, secret, systems_json, disabled, "order", label, last_at, last_ok, last_status, last_error, last_ok_at FROM webhooks WHERE disabled = 0 ORDER BY "order" ASC, id ASC
`

func (q *Queries) ListActiveWebhooks(ctx context.Context) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listActiveWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Type,
			&i.Secret,
			&i.SystemsJson,
			&i.Disabled,
			&i.Order,
			&i.Label,
			&i.LastAt,
			&i.LastOk,
			&i.LastStatus,
			&i.LastError,
			&i.LastOkAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, url, type, secret, systems_json, disabled, "order", label, last_at, last_ok, last_status, last_error, last_ok_at FROM webhooks ORDER BY "order" ASC, id ASC
`

func (q *Queries) ListWebhooks(ctx context.Context) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Type,
			&i.Secret,
			&i.SystemsJson,
			&i.Disabled,
			&i.Order,
			&i.Label,
			&i.LastAt,
			&i.LastOk,
			&i.LastStatus,
			&i.LastError,
			&i.LastOkAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordWebhookDelivery = `-- name: RecordWebhookDelivery :exec
UPDATE webhooks SET
    last_at     = ?1,
    last_ok     = ?2,
    last_status = ?3,
    last_error  = ?4,
    last_ok_at  = CASE WHEN ?2 = 1 THEN ?1 ELSE last_ok_at END
WHERE id = ?5
`

type RecordWebhookDeliveryParams struct {
	At     sql.NullInt64 `db:"at" json:"at"`
	Ok     int64         `db:"ok" json:"ok"`
	Status int64         `db:"status" json:"status"`
	Error  string        `db:"error" json:"error"`
	ID     int64         `db:"id" json:"id"`
}

func (q *Queries) RecordWebhookDelivery(ctx context.Context, arg RecordWebhookDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, recordWebhookDelivery,
		arg.At,
		arg.Ok,
		arg.Status,
		arg.Error,
		arg.ID,
	)
	return err
}

const updateWebhook = `-- name: UpdateWebhook :exec
UPDATE webhooks SET
    url          = ?1,
    type         = ?2,
    secret       = ?3,
    systems_json = ?4,
    disabled     = ?5,
    "order"      = ?6,
    label        = ?7
WHERE id = ?8
`

type UpdateWebhookParams struct {
	Url         string         `db:"url" json:"url"`
	Type        string         `db:"type" json:"type"`
	Secret      sql.NullString `db:"secret" json:"secret"`
	SystemsJson sql.NullString `db:"systems_json" json:"systems_json"`
	Disabled    int64          `db:"disabled" json:"disabled"`
	Order       int64          `db:"order" json:"order"`
	Label       string         `db:"label" json:"label"`
	ID          int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) error {
	_, err := q.db.ExecContext(ctx, updateWebhook,
		arg.Url,
		arg.Type,
		arg.Secret,
		arg.SystemsJson,
		arg.Disabled,
		arg.Order,
		arg.Label,
		arg.ID,
	)
	return err
}
